services:
  comfyui:
    build:
      context: ./comfyui
      dockerfile: Dockerfile
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./comfyui/ComfyUI:/ComfyUI
    environment:
      - TZ=Asia/Tokyo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
